### ISSUE TITLE
Issues with self-hosting

### ISSUE THREAD

**Issue by Conceded2** [PrivacySafe/sticktock#5]
Firstly, I would like to commend you on the outstanding work being done with the StickTock project.

I am currently experiencing challenges while attempting to self-host StickTock on a custom domain. Specifically, I have set up StickTock using Docker with an Nginx reverse proxy, following the instructions provided in the README file and utilizing `docker compose up` to initiate the containers.

However, when I make a request to `https://sticktock-api.mydomain.com/latest`, I receive a null response. In contrast, a request to your StickTock instance `https://api.sticktock.com/latest` returns the expected JSON response: `{"id":7071,"tiktokId":"7455728272291155208","type":"video"}`.

Additionally, when I attempt to view a random video, such as `https://sticktock.mydomain.com/post/1234`, I encounter an error in the Docker logs.

```
sticktock-api     |
sticktock-api     | > sticktock-api@1.0.0 start
sticktock-api     | > DATABASE_URL="file:/var/local/sticktock/prisma-db.sqlite" node dist/index.js
sticktock-api     |
sticktock-api     | Creating symlink to /var/local/sticktock/public at path public
sticktock-api     | (node:19) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
sticktock-api     | (Use `node --trace-deprecation ...` to show where the warning was created)
sticktock-api     | StickTock API server running on port 2000
sticktock-webapp  |
sticktock-webapp  | > sticktock@0.1.0 start
sticktock-webapp  | > next start
sticktock-webapp  |
sticktock-webapp  |   ▲ Next.js 14.2.5
sticktock-webapp  |   - Local:        http://localhost:3000
sticktock-webapp  |
sticktock-webapp  |  ✓ Starting...
sticktock-webapp  |  ✓ Ready in 406ms
sticktock-api     | null
sticktock-api     | null
sticktock-webapp  | {
sticktock-webapp  |   data: {
sticktock-webapp  |     issues: [
sticktock-webapp  |       [Object], [Object],
sticktock-webapp  |       [Object], [Object],
sticktock-webapp  |       [Object], [Object],
sticktock-webapp  |       [Object], [Object]
sticktock-webapp  |     ],
sticktock-webapp  |     name: 'ZodError'
sticktock-webapp  |   }
sticktock-webapp  | }
sticktock-api     | null
```
<details>
<summary>docker-compose.yml</summary>

```
version: '3.8'

services:

  sticktock-webapp:
    image: sticktock-webapp
    container_name: sticktock-webapp
    ports:
      - '127.0.0.1:3000:3000'

  sticktock-api:
    image: sticktock-api
    container_name: sticktock-api
    ports:
      - '127.0.0.1:2000:2000'
    volumes:
      - /var/local/sticktock-api-data:/var/local/sticktock/
```

</details>
<details>
<summary>service.config.ts</summary>

```
export const BASE_DOMAIN = 'mydomain.com';

export const FRONTEND_URL_FOR_BROWSER = `https://sticktock.${BASE_DOMAIN}`;
export const FRONTEND_URL_FOR_SERVER_SELF = `http://sticktock-webapp:3000`;

export const API_URL_FOR_BROWSER = `https://sticktock-api.${BASE_DOMAIN}`;
export const API_URL_FOR_SERVER = `http://sticktock-api:2000`;

```
</details>
